In [1]:
from src.models.lbcnn.lbcnn_parts import ConvLBP
from src.models.dsc.dsc_lbc_unet import DSCConvLBP
import torch.nn as nn
import torch

In [30]:
layer1 = nn.Conv2d(3, 3, kernel_size=3)
layer2 = ConvLBP(3, 3)

In [1]:
print(layer1.weight.data.numpy().shape)
print(layer2.weight.data.numpy().shape)

NameError: name 'layer1' is not defined

In [32]:
weights1 = layer1.weight.data.numpy()
weights2 = layer2.weight.data.numpy()

In [33]:
weights1[0]

array([[[-0.16135396, -0.0464388 , -0.06492198],
        [ 0.00832314,  0.11083342,  0.064671  ],
        [ 0.01963076,  0.10890828, -0.05856703]],

       [[ 0.1908251 ,  0.16622601,  0.1073497 ],
        [-0.18438329, -0.10498405,  0.00216952],
        [ 0.02143887, -0.08640892,  0.15908188]],

       [[-0.02085519,  0.13306558,  0.10958765],
        [ 0.17862745, -0.10089059,  0.01201264],
        [-0.04580659,  0.16135   , -0.03892624]]], dtype=float32)

In [34]:
weights2[0]

array([[[ 0.,  1., -1.],
        [ 1., -1.,  0.],
        [ 0.,  0., -1.]],

       [[ 0.,  0.,  0.],
        [-1.,  1.,  0.],
        [ 0.,  1.,  0.]],

       [[-1.,  0.,  1.],
        [-1., -1., -1.],
        [-1., -1.,  0.]]], dtype=float32)

In [35]:
weights = next(layer1.parameters())

In [43]:
matrix_proba = torch.FloatTensor(weights.data.shape).fill_(0.5)

In [50]:
binary_weights = torch.bernoulli(matrix_proba) * 2 - 1

In [52]:
torch.rand(matrix_proba.shape) > 0.5

tensor([[[[False, False, False],
          [ True, False,  True],
          [False, False, False]],

         [[ True,  True, False],
          [ True, False, False],
          [ True,  True, False]],

         [[ True, False,  True],
          [ True, False, False],
          [ True,  True,  True]]],


        [[[ True, False,  True],
          [False,  True,  True],
          [False,  True,  True]],

         [[ True, False,  True],
          [ True,  True,  True],
          [ True, False, False]],

         [[False,  True, False],
          [False,  True, False],
          [False, False, False]]],


        [[[False, False,  True],
          [ True, False,  True],
          [False, False, False]],

         [[False, False,  True],
          [ True,  True, False],
          [ True,  True,  True]],

         [[ True, False, False],
          [False, False,  True],
          [False,  True, False]]]])

In [54]:
nn.Conv2d(3, 64, kernel_size=1).weight.data.numpy().shape

(64, 3, 1, 1)